### ISSUE TITLE
VMG error: 45 character limit on page titles

### ISSUE THREAD

**Issue by arfaanrd** [reason-digital/virgin-money-giving-api#3]
Error: VMG has responded with an error. Please check the exception. The VMG API responded with the error code: 003.01.05 and the message is: A valid page title up to 45 characters is required.

**Comment by tommym9** [comment]
The VMG API won't allow a page title to be longer than 45 characters. This package should reflect that.

Todo:
- Add a character count and throw exception in src/Models/Page.php setPageTitle()
- Add a test in tests/Models/PageTest.php that the exception is thrown and that titles under 45 characters are accepted
